### PR TITLE
chore: CI - unit.yml - move bundle install into ruby/setup-ruby, use PS in Windows

### PR DESCRIPTION
**Pull request by MSP-Greg**
1. ruby/setup-ruby - use `bundler-cache: true`, remove `bundle install` from other steps
2. actions/checkout@v2 -> actions/checkout@v3
3. actions/setup-go@v2 -> actions/setup-go@v3

### CODE REVIEW

**Comment by MSP-Greg** [comment]
See https://github.com/MSP-Greg/functions-framework-ruby/actions/runs/2869018368 for a passing run in my fork.

Using caching for `bundle install` should speed up CI.  Caches are flushed/deleted, not sure of the time frame.  There is also an input in ruby/setup-ruby that can be used to flush them if they become corrupt.

**Comment by dazuma** [comment]
Switching to bundler-cache sounds good to me.

**Comment by dazuma** [comment]
I think we can fix the lint job by excluding the vendored bundle from it. In `/.rubocop.yml`, add the following line under AllCops->Exclude:

```
    - "vendor/bundle/**/*.rb"
    - "vendor/bundle/**/.rubocop.yml"
```

**Comment by MSP-Greg** [comment]
Done.  Thanks.

**Comment by dazuma** [comment]
Argh, the linter is still unhappy. Sorry about this; I'll take a look.

**Comment by MSP-Greg** [comment]
Puma uses `**/vendor/bundle/**/*`, and we've also got `vendor/` in .gitignore?

**Comment by dazuma** [comment]
Yeah looks like instead of what I told you, add this line instead:

```
    - "vendor/bundle/**/*"
```

**Comment by dazuma** [comment]
Or what you did should work as well.

**Comment by MSP-Greg** [comment]
Wasn't sure if `"examples/*/vendor/**/*.rb"` could be removed?

**Review by dazuma — APPROVED** [review]
Thanks!

**Comment by MSP-Greg** [comment]
JFYI,  the following line in lint.yml & unit.yml really makes it a PITA to run CI in one's fork...
```
if: ${{ github.repository == 'GoogleCloudPlatform/functions-framework-ruby' }}
```

**Pull request merged**
